### ISSUE TITLE
怎么使用

### ISSUE THREAD

**Issue by aaaaamilk** [ocyisheng/FaceFusion-ChineseWording#1]
你好能不能详细说一下怎么使用？

**Comment by aaaaamilk** [comment]
就是具体修改哪个地方的代码

**Comment by ocyisheng** [comment]
替换wording.py文件发自我的 iPhone在 2024年12月3日，10:00，aaaaamilk ***@***.***> 写道：﻿
你好能不能详细说一下怎么使用？
